/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAgbRouteImport } from './routes/$locale.agb'
import { Route as LocaleDatenschutzRouteImport } from './routes/$locale.datenschutz'
import { Route as LocaleErbenRouteImport } from './routes/$locale.erben'
import { Route as LocaleImmobilienbewertungRouteImport } from './routes/$locale.immobilienbewertung'
import { Route as LocaleImpressumRouteImport } from './routes/$locale.impressum'
import { Route as LocaleKontaktRouteImport } from './routes/$locale.kontakt'
import { Route as LocaleUeberMichRouteImport } from './routes/$locale.ueber-mich'
import { Route as LocaleVerkaufenRouteImport } from './routes/$locale.verkaufen'
import { Route as LocaleVerkauftRouteImport } from './routes/$locale.verkauft'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSetPasswordRouteImport } from './routes/admin.set-password'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale.admin.index'
import { Route as LocaleAdminSplatRouteImport } from './routes/$locale.admin.$'
import { Route as LocaleAuthSplatRouteImport } from './routes/$locale.auth.$'
import { Route as LocaleImmobilienIndexRouteImport } from './routes/$locale.immobilien.index'
import { Route as LocaleImmobilienSlugRouteImport } from './routes/$locale.immobilien.$slug'
import { Route as LocaleRatgeberIndexRouteImport } from './routes/$locale.ratgeber.index'
import { Route as LocaleRatgeberSlugRouteImport } from './routes/$locale.ratgeber.$slug'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin._authenticated.index'
import { Route as AdminAuthenticatedAnalyticsRouteImport } from './routes/admin._authenticated.analytics'
import { Route as AdminAuthenticatedCalendarRouteImport } from './routes/admin._authenticated.calendar'
import { Route as AdminAuthenticatedInquiriesRouteImport } from './routes/admin._authenticated.inquiries'
import { Route as AdminAuthenticatedListingsRouteImport } from './routes/admin._authenticated.listings'
import { Route as AdminAuthenticatedPostsRouteImport } from './routes/admin._authenticated.posts'
import { Route as AdminAuthenticatedSettingsRouteImport } from './routes/admin._authenticated.settings'
import { Route as AdminAuthenticatedTestimonialsRouteImport } from './routes/admin._authenticated.testimonials'
import { Route as AdminAuthenticatedUsersRouteImport } from './routes/admin._authenticated.users'
import { Route as ApiPublicTrackViewRouteImport } from './routes/api/public/track-view'
import { Route as AdminAuthenticatedInquiriesIndexRouteImport } from './routes/admin._authenticated.inquiries.index'
import { Route as AdminAuthenticatedInquiriesIdRouteImport } from './routes/admin._authenticated.inquiries.$id'
import { Route as AdminAuthenticatedListingsIndexRouteImport } from './routes/admin._authenticated.listings.index'
import { Route as AdminAuthenticatedListingsIdRouteImport } from './routes/admin._authenticated.listings.$id'
import { Route as AdminAuthenticatedListingsNewRouteImport } from './routes/admin._authenticated.listings.new'
import { Route as AdminAuthenticatedSettingsIndexRouteImport } from './routes/admin._authenticated.settings.index'
import { Route as AdminAuthenticatedSettingsTabRouteImport } from './routes/admin._authenticated.settings.$tab'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAgbRoute = LocaleAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDatenschutzRoute = LocaleDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleErbenRoute = LocaleErbenRouteImport.update({
  id: '/erben',
  path: '/erben',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImmobilienbewertungRoute =
  LocaleImmobilienbewertungRouteImport.update({
    id: '/immobilienbewertung',
    path: '/immobilienbewertung',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleImpressumRoute = LocaleImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleKontaktRoute = LocaleKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUeberMichRoute = LocaleUeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVerkaufenRoute = LocaleVerkaufenRouteImport.update({
  id: '/verkaufen',
  path: '/verkaufen',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVerkauftRoute = LocaleVerkauftRouteImport.update({
  id: '/verkauft',
  path: '/verkauft',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminSplatRoute = LocaleAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthSplatRoute = LocaleAuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImmobilienIndexRoute = LocaleImmobilienIndexRouteImport.update({
  id: '/immobilien/',
  path: '/immobilien/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImmobilienSlugRoute = LocaleImmobilienSlugRouteImport.update({
  id: '/immobilien/$slug',
  path: '/immobilien/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRatgeberIndexRoute = LocaleRatgeberIndexRouteImport.update({
  id: '/ratgeber/',
  path: '/ratgeber/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRatgeberSlugRoute = LocaleRatgeberSlugRouteImport.update({
  id: '/ratgeber/$slug',
  path: '/ratgeber/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedAnalyticsRoute =
  AdminAuthenticatedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCalendarRoute =
  AdminAuthenticatedCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedInquiriesRoute =
  AdminAuthenticatedInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedListingsRoute =
  AdminAuthenticatedListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedPostsRoute = AdminAuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedSettingsRoute =
  AdminAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedTestimonialsRoute =
  AdminAuthenticatedTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedUsersRoute = AdminAuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const ApiPublicTrackViewRoute = ApiPublicTrackViewRouteImport.update({
  id: '/api/public/track-view',
  path: '/api/public/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedInquiriesIndexRoute =
  AdminAuthenticatedInquiriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedInquiriesRoute,
  } as any)
const AdminAuthenticatedInquiriesIdRoute =
  AdminAuthenticatedInquiriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthenticatedInquiriesRoute,
  } as any)
const AdminAuthenticatedListingsIndexRoute =
  AdminAuthenticatedListingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedListingsRoute,
  } as any)
const AdminAuthenticatedListingsIdRoute =
  AdminAuthenticatedListingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthenticatedListingsRoute,
  } as any)
const AdminAuthenticatedListingsNewRoute =
  AdminAuthenticatedListingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAuthenticatedListingsRoute,
  } as any)
const AdminAuthenticatedSettingsIndexRoute =
  AdminAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedSettingsRoute,
  } as any)
const AdminAuthenticatedSettingsTabRoute =
  AdminAuthenticatedSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AdminAuthenticatedSettingsRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/agb': typeof LocaleAgbRoute
  '/$locale/datenschutz': typeof LocaleDatenschutzRoute
  '/$locale/erben': typeof LocaleErbenRoute
  '/$locale/immobilienbewertung': typeof LocaleImmobilienbewertungRoute
  '/$locale/impressum': typeof LocaleImpressumRoute
  '/$locale/kontakt': typeof LocaleKontaktRoute
  '/$locale/ueber-mich': typeof LocaleUeberMichRoute
  '/$locale/verkaufen': typeof LocaleVerkaufenRoute
  '/$locale/verkauft': typeof LocaleVerkauftRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/$': typeof LocaleAdminSplatRoute
  '/$locale/auth/$': typeof LocaleAuthSplatRoute
  '/$locale/immobilien/$slug': typeof LocaleImmobilienSlugRoute
  '/$locale/ratgeber/$slug': typeof LocaleRatgeberSlugRoute
  '/admin/analytics': typeof AdminAuthenticatedAnalyticsRoute
  '/admin/calendar': typeof AdminAuthenticatedCalendarRoute
  '/admin/inquiries': typeof AdminAuthenticatedInquiriesRouteWithChildren
  '/admin/listings': typeof AdminAuthenticatedListingsRouteWithChildren
  '/admin/posts': typeof AdminAuthenticatedPostsRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRouteWithChildren
  '/admin/testimonials': typeof AdminAuthenticatedTestimonialsRoute
  '/admin/users': typeof AdminAuthenticatedUsersRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/immobilien/': typeof LocaleImmobilienIndexRoute
  '/$locale/ratgeber/': typeof LocaleRatgeberIndexRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/inquiries/$id': typeof AdminAuthenticatedInquiriesIdRoute
  '/admin/listings/$id': typeof AdminAuthenticatedListingsIdRoute
  '/admin/listings/new': typeof AdminAuthenticatedListingsNewRoute
  '/admin/settings/$tab': typeof AdminAuthenticatedSettingsTabRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/inquiries/': typeof AdminAuthenticatedInquiriesIndexRoute
  '/admin/listings/': typeof AdminAuthenticatedListingsIndexRoute
  '/admin/settings/': typeof AdminAuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/agb': typeof LocaleAgbRoute
  '/$locale/datenschutz': typeof LocaleDatenschutzRoute
  '/$locale/erben': typeof LocaleErbenRoute
  '/$locale/immobilienbewertung': typeof LocaleImmobilienbewertungRoute
  '/$locale/impressum': typeof LocaleImpressumRoute
  '/$locale/kontakt': typeof LocaleKontaktRoute
  '/$locale/ueber-mich': typeof LocaleUeberMichRoute
  '/$locale/verkaufen': typeof LocaleVerkaufenRoute
  '/$locale/verkauft': typeof LocaleVerkauftRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/$': typeof LocaleAdminSplatRoute
  '/$locale/auth/$': typeof LocaleAuthSplatRoute
  '/$locale/immobilien/$slug': typeof LocaleImmobilienSlugRoute
  '/$locale/ratgeber/$slug': typeof LocaleRatgeberSlugRoute
  '/admin/analytics': typeof AdminAuthenticatedAnalyticsRoute
  '/admin/calendar': typeof AdminAuthenticatedCalendarRoute
  '/admin/posts': typeof AdminAuthenticatedPostsRoute
  '/admin/testimonials': typeof AdminAuthenticatedTestimonialsRoute
  '/admin/users': typeof AdminAuthenticatedUsersRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/$locale/admin': typeof LocaleAdminIndexRoute
  '/$locale/immobilien': typeof LocaleImmobilienIndexRoute
  '/$locale/ratgeber': typeof LocaleRatgeberIndexRoute
  '/admin/inquiries/$id': typeof AdminAuthenticatedInquiriesIdRoute
  '/admin/listings/$id': typeof AdminAuthenticatedListingsIdRoute
  '/admin/listings/new': typeof AdminAuthenticatedListingsNewRoute
  '/admin/settings/$tab': typeof AdminAuthenticatedSettingsTabRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/inquiries': typeof AdminAuthenticatedInquiriesIndexRoute
  '/admin/listings': typeof AdminAuthenticatedListingsIndexRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/agb': typeof LocaleAgbRoute
  '/$locale/datenschutz': typeof LocaleDatenschutzRoute
  '/$locale/erben': typeof LocaleErbenRoute
  '/$locale/immobilienbewertung': typeof LocaleImmobilienbewertungRoute
  '/$locale/impressum': typeof LocaleImpressumRoute
  '/$locale/kontakt': typeof LocaleKontaktRoute
  '/$locale/ueber-mich': typeof LocaleUeberMichRoute
  '/$locale/verkaufen': typeof LocaleVerkaufenRoute
  '/$locale/verkauft': typeof LocaleVerkauftRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/$': typeof LocaleAdminSplatRoute
  '/$locale/auth/$': typeof LocaleAuthSplatRoute
  '/$locale/immobilien/$slug': typeof LocaleImmobilienSlugRoute
  '/$locale/ratgeber/$slug': typeof LocaleRatgeberSlugRoute
  '/admin/_authenticated/analytics': typeof AdminAuthenticatedAnalyticsRoute
  '/admin/_authenticated/calendar': typeof AdminAuthenticatedCalendarRoute
  '/admin/_authenticated/inquiries': typeof AdminAuthenticatedInquiriesRouteWithChildren
  '/admin/_authenticated/listings': typeof AdminAuthenticatedListingsRouteWithChildren
  '/admin/_authenticated/posts': typeof AdminAuthenticatedPostsRoute
  '/admin/_authenticated/settings': typeof AdminAuthenticatedSettingsRouteWithChildren
  '/admin/_authenticated/testimonials': typeof AdminAuthenticatedTestimonialsRoute
  '/admin/_authenticated/users': typeof AdminAuthenticatedUsersRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/immobilien/': typeof LocaleImmobilienIndexRoute
  '/$locale/ratgeber/': typeof LocaleRatgeberIndexRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/inquiries/$id': typeof AdminAuthenticatedInquiriesIdRoute
  '/admin/_authenticated/listings/$id': typeof AdminAuthenticatedListingsIdRoute
  '/admin/_authenticated/listings/new': typeof AdminAuthenticatedListingsNewRoute
  '/admin/_authenticated/settings/$tab': typeof AdminAuthenticatedSettingsTabRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/_authenticated/inquiries/': typeof AdminAuthenticatedInquiriesIndexRoute
  '/admin/_authenticated/listings/': typeof AdminAuthenticatedListingsIndexRoute
  '/admin/_authenticated/settings/': typeof AdminAuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/sitemap.xml'
    | '/$locale/agb'
    | '/$locale/datenschutz'
    | '/$locale/erben'
    | '/$locale/immobilienbewertung'
    | '/$locale/impressum'
    | '/$locale/kontakt'
    | '/$locale/ueber-mich'
    | '/$locale/verkaufen'
    | '/$locale/verkauft'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/set-password'
    | '/$locale/'
    | '/$locale/admin/$'
    | '/$locale/auth/$'
    | '/$locale/immobilien/$slug'
    | '/$locale/ratgeber/$slug'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/inquiries'
    | '/admin/listings'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/api/public/track-view'
    | '/$locale/admin/'
    | '/$locale/immobilien/'
    | '/$locale/ratgeber/'
    | '/admin/'
    | '/admin/inquiries/$id'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/settings/$tab'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/inquiries/'
    | '/admin/listings/'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/$locale/agb'
    | '/$locale/datenschutz'
    | '/$locale/erben'
    | '/$locale/immobilienbewertung'
    | '/$locale/impressum'
    | '/$locale/kontakt'
    | '/$locale/ueber-mich'
    | '/$locale/verkaufen'
    | '/$locale/verkauft'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/set-password'
    | '/$locale'
    | '/$locale/admin/$'
    | '/$locale/auth/$'
    | '/$locale/immobilien/$slug'
    | '/$locale/ratgeber/$slug'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/posts'
    | '/admin/testimonials'
    | '/admin/users'
    | '/api/public/track-view'
    | '/$locale/admin'
    | '/$locale/immobilien'
    | '/$locale/ratgeber'
    | '/admin/inquiries/$id'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/settings/$tab'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/inquiries'
    | '/admin/listings'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/sitemap.xml'
    | '/$locale/agb'
    | '/$locale/datenschutz'
    | '/$locale/erben'
    | '/$locale/immobilienbewertung'
    | '/$locale/impressum'
    | '/$locale/kontakt'
    | '/$locale/ueber-mich'
    | '/$locale/verkaufen'
    | '/$locale/verkauft'
    | '/admin/_authenticated'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/set-password'
    | '/$locale/'
    | '/$locale/admin/$'
    | '/$locale/auth/$'
    | '/$locale/immobilien/$slug'
    | '/$locale/ratgeber/$slug'
    | '/admin/_authenticated/analytics'
    | '/admin/_authenticated/calendar'
    | '/admin/_authenticated/inquiries'
    | '/admin/_authenticated/listings'
    | '/admin/_authenticated/posts'
    | '/admin/_authenticated/settings'
    | '/admin/_authenticated/testimonials'
    | '/admin/_authenticated/users'
    | '/api/public/track-view'
    | '/$locale/admin/'
    | '/$locale/immobilien/'
    | '/$locale/ratgeber/'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/inquiries/$id'
    | '/admin/_authenticated/listings/$id'
    | '/admin/_authenticated/listings/new'
    | '/admin/_authenticated/settings/$tab'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/_authenticated/inquiries/'
    | '/admin/_authenticated/listings/'
    | '/admin/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicTrackViewRoute: typeof ApiPublicTrackViewRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/agb': {
      id: '/$locale/agb'
      path: '/agb'
      fullPath: '/$locale/agb'
      preLoaderRoute: typeof LocaleAgbRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/datenschutz': {
      id: '/$locale/datenschutz'
      path: '/datenschutz'
      fullPath: '/$locale/datenschutz'
      preLoaderRoute: typeof LocaleDatenschutzRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/erben': {
      id: '/$locale/erben'
      path: '/erben'
      fullPath: '/$locale/erben'
      preLoaderRoute: typeof LocaleErbenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/immobilienbewertung': {
      id: '/$locale/immobilienbewertung'
      path: '/immobilienbewertung'
      fullPath: '/$locale/immobilienbewertung'
      preLoaderRoute: typeof LocaleImmobilienbewertungRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/impressum': {
      id: '/$locale/impressum'
      path: '/impressum'
      fullPath: '/$locale/impressum'
      preLoaderRoute: typeof LocaleImpressumRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/kontakt': {
      id: '/$locale/kontakt'
      path: '/kontakt'
      fullPath: '/$locale/kontakt'
      preLoaderRoute: typeof LocaleKontaktRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ueber-mich': {
      id: '/$locale/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/$locale/ueber-mich'
      preLoaderRoute: typeof LocaleUeberMichRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/verkaufen': {
      id: '/$locale/verkaufen'
      path: '/verkaufen'
      fullPath: '/$locale/verkaufen'
      preLoaderRoute: typeof LocaleVerkaufenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/verkauft': {
      id: '/$locale/verkauft'
      path: '/verkauft'
      fullPath: '/$locale/verkauft'
      preLoaderRoute: typeof LocaleVerkauftRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/$': {
      id: '/$locale/admin/$'
      path: '/admin/$'
      fullPath: '/$locale/admin/$'
      preLoaderRoute: typeof LocaleAdminSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/$': {
      id: '/$locale/auth/$'
      path: '/auth/$'
      fullPath: '/$locale/auth/$'
      preLoaderRoute: typeof LocaleAuthSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/immobilien/': {
      id: '/$locale/immobilien/'
      path: '/immobilien'
      fullPath: '/$locale/immobilien/'
      preLoaderRoute: typeof LocaleImmobilienIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/immobilien/$slug': {
      id: '/$locale/immobilien/$slug'
      path: '/immobilien/$slug'
      fullPath: '/$locale/immobilien/$slug'
      preLoaderRoute: typeof LocaleImmobilienSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ratgeber/': {
      id: '/$locale/ratgeber/'
      path: '/ratgeber'
      fullPath: '/$locale/ratgeber/'
      preLoaderRoute: typeof LocaleRatgeberIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ratgeber/$slug': {
      id: '/$locale/ratgeber/$slug'
      path: '/ratgeber/$slug'
      fullPath: '/$locale/ratgeber/$slug'
      preLoaderRoute: typeof LocaleRatgeberSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/analytics': {
      id: '/admin/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthenticatedAnalyticsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/calendar': {
      id: '/admin/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminAuthenticatedCalendarRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/inquiries': {
      id: '/admin/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminAuthenticatedInquiriesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/listings': {
      id: '/admin/_authenticated/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminAuthenticatedListingsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/posts': {
      id: '/admin/_authenticated/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminAuthenticatedPostsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/settings': {
      id: '/admin/_authenticated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthenticatedSettingsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/testimonials': {
      id: '/admin/_authenticated/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminAuthenticatedTestimonialsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/users': {
      id: '/admin/_authenticated/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthenticatedUsersRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/api/public/track-view': {
      id: '/api/public/track-view'
      path: '/api/public/track-view'
      fullPath: '/api/public/track-view'
      preLoaderRoute: typeof ApiPublicTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/inquiries/': {
      id: '/admin/_authenticated/inquiries/'
      path: '/'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminAuthenticatedInquiriesIndexRouteImport
      parentRoute: typeof AdminAuthenticatedInquiriesRoute
    }
    '/admin/_authenticated/inquiries/$id': {
      id: '/admin/_authenticated/inquiries/$id'
      path: '/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminAuthenticatedInquiriesIdRouteImport
      parentRoute: typeof AdminAuthenticatedInquiriesRoute
    }
    '/admin/_authenticated/listings/': {
      id: '/admin/_authenticated/listings/'
      path: '/'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminAuthenticatedListingsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedListingsRoute
    }
    '/admin/_authenticated/listings/$id': {
      id: '/admin/_authenticated/listings/$id'
      path: '/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminAuthenticatedListingsIdRouteImport
      parentRoute: typeof AdminAuthenticatedListingsRoute
    }
    '/admin/_authenticated/listings/new': {
      id: '/admin/_authenticated/listings/new'
      path: '/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminAuthenticatedListingsNewRouteImport
      parentRoute: typeof AdminAuthenticatedListingsRoute
    }
    '/admin/_authenticated/settings/': {
      id: '/admin/_authenticated/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedSettingsRoute
    }
    '/admin/_authenticated/settings/$tab': {
      id: '/admin/_authenticated/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AdminAuthenticatedSettingsTabRouteImport
      parentRoute: typeof AdminAuthenticatedSettingsRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteChildren {
  LocaleAgbRoute: typeof LocaleAgbRoute
  LocaleDatenschutzRoute: typeof LocaleDatenschutzRoute
  LocaleErbenRoute: typeof LocaleErbenRoute
  LocaleImmobilienbewertungRoute: typeof LocaleImmobilienbewertungRoute
  LocaleImpressumRoute: typeof LocaleImpressumRoute
  LocaleKontaktRoute: typeof LocaleKontaktRoute
  LocaleUeberMichRoute: typeof LocaleUeberMichRoute
  LocaleVerkaufenRoute: typeof LocaleVerkaufenRoute
  LocaleVerkauftRoute: typeof LocaleVerkauftRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAdminSplatRoute: typeof LocaleAdminSplatRoute
  LocaleAuthSplatRoute: typeof LocaleAuthSplatRoute
  LocaleImmobilienSlugRoute: typeof LocaleImmobilienSlugRoute
  LocaleRatgeberSlugRoute: typeof LocaleRatgeberSlugRoute
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
  LocaleImmobilienIndexRoute: typeof LocaleImmobilienIndexRoute
  LocaleRatgeberIndexRoute: typeof LocaleRatgeberIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAgbRoute: LocaleAgbRoute,
  LocaleDatenschutzRoute: LocaleDatenschutzRoute,
  LocaleErbenRoute: LocaleErbenRoute,
  LocaleImmobilienbewertungRoute: LocaleImmobilienbewertungRoute,
  LocaleImpressumRoute: LocaleImpressumRoute,
  LocaleKontaktRoute: LocaleKontaktRoute,
  LocaleUeberMichRoute: LocaleUeberMichRoute,
  LocaleVerkaufenRoute: LocaleVerkaufenRoute,
  LocaleVerkauftRoute: LocaleVerkauftRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAdminSplatRoute: LocaleAdminSplatRoute,
  LocaleAuthSplatRoute: LocaleAuthSplatRoute,
  LocaleImmobilienSlugRoute: LocaleImmobilienSlugRoute,
  LocaleRatgeberSlugRoute: LocaleRatgeberSlugRoute,
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
  LocaleImmobilienIndexRoute: LocaleImmobilienIndexRoute,
  LocaleRatgeberIndexRoute: LocaleRatgeberIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminAuthenticatedInquiriesRouteChildren {
  AdminAuthenticatedInquiriesIdRoute: typeof AdminAuthenticatedInquiriesIdRoute
  AdminAuthenticatedInquiriesIndexRoute: typeof AdminAuthenticatedInquiriesIndexRoute
}

const AdminAuthenticatedInquiriesRouteChildren: AdminAuthenticatedInquiriesRouteChildren =
  {
    AdminAuthenticatedInquiriesIdRoute: AdminAuthenticatedInquiriesIdRoute,
    AdminAuthenticatedInquiriesIndexRoute:
      AdminAuthenticatedInquiriesIndexRoute,
  }

const AdminAuthenticatedInquiriesRouteWithChildren =
  AdminAuthenticatedInquiriesRoute._addFileChildren(
    AdminAuthenticatedInquiriesRouteChildren,
  )

interface AdminAuthenticatedListingsRouteChildren {
  AdminAuthenticatedListingsIdRoute: typeof AdminAuthenticatedListingsIdRoute
  AdminAuthenticatedListingsNewRoute: typeof AdminAuthenticatedListingsNewRoute
  AdminAuthenticatedListingsIndexRoute: typeof AdminAuthenticatedListingsIndexRoute
}

const AdminAuthenticatedListingsRouteChildren: AdminAuthenticatedListingsRouteChildren =
  {
    AdminAuthenticatedListingsIdRoute: AdminAuthenticatedListingsIdRoute,
    AdminAuthenticatedListingsNewRoute: AdminAuthenticatedListingsNewRoute,
    AdminAuthenticatedListingsIndexRoute: AdminAuthenticatedListingsIndexRoute,
  }

const AdminAuthenticatedListingsRouteWithChildren =
  AdminAuthenticatedListingsRoute._addFileChildren(
    AdminAuthenticatedListingsRouteChildren,
  )

interface AdminAuthenticatedSettingsRouteChildren {
  AdminAuthenticatedSettingsTabRoute: typeof AdminAuthenticatedSettingsTabRoute
  AdminAuthenticatedSettingsIndexRoute: typeof AdminAuthenticatedSettingsIndexRoute
}

const AdminAuthenticatedSettingsRouteChildren: AdminAuthenticatedSettingsRouteChildren =
  {
    AdminAuthenticatedSettingsTabRoute: AdminAuthenticatedSettingsTabRoute,
    AdminAuthenticatedSettingsIndexRoute: AdminAuthenticatedSettingsIndexRoute,
  }

const AdminAuthenticatedSettingsRouteWithChildren =
  AdminAuthenticatedSettingsRoute._addFileChildren(
    AdminAuthenticatedSettingsRouteChildren,
  )

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedAnalyticsRoute: typeof AdminAuthenticatedAnalyticsRoute
  AdminAuthenticatedCalendarRoute: typeof AdminAuthenticatedCalendarRoute
  AdminAuthenticatedInquiriesRoute: typeof AdminAuthenticatedInquiriesRouteWithChildren
  AdminAuthenticatedListingsRoute: typeof AdminAuthenticatedListingsRouteWithChildren
  AdminAuthenticatedPostsRoute: typeof AdminAuthenticatedPostsRoute
  AdminAuthenticatedSettingsRoute: typeof AdminAuthenticatedSettingsRouteWithChildren
  AdminAuthenticatedTestimonialsRoute: typeof AdminAuthenticatedTestimonialsRoute
  AdminAuthenticatedUsersRoute: typeof AdminAuthenticatedUsersRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedAnalyticsRoute: AdminAuthenticatedAnalyticsRoute,
  AdminAuthenticatedCalendarRoute: AdminAuthenticatedCalendarRoute,
  AdminAuthenticatedInquiriesRoute:
    AdminAuthenticatedInquiriesRouteWithChildren,
  AdminAuthenticatedListingsRoute: AdminAuthenticatedListingsRouteWithChildren,
  AdminAuthenticatedPostsRoute: AdminAuthenticatedPostsRoute,
  AdminAuthenticatedSettingsRoute: AdminAuthenticatedSettingsRouteWithChildren,
  AdminAuthenticatedTestimonialsRoute: AdminAuthenticatedTestimonialsRoute,
  AdminAuthenticatedUsersRoute: AdminAuthenticatedUsersRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicTrackViewRoute: ApiPublicTrackViewRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
